Pv-Final/EasyFitHub/EasyFitHub/Controllers/GymsController.cs
using Microsoft.AspNetCore.Mvc;
using EasyFitHub.Data;
using EasyFitHub.Models.Gym;
using EasyFitHub.Models.Account;
using EasyFitHub.Services;
using EasyFitHub.Models.Profile;
using System;
using EasyFitHub.Models.Miscalenous;


namespace EasyFitHub.Controllers
{
    /// <summary>
    /// Author: Rui Barroso
    /// Controlador usado para gerir Ginásios
    /// </summary>
    public class GymsController : Controller
    {
        private readonly GymsInfo _gymsInfo;
        private readonly AuthenticationService _authenticationService;
        private readonly AuthorizationService _authorizationService;
        private readonly ILogger<GymsController> _logger;
        private readonly FirebaseService _firebaseService;

        public GymsController(EasyFitHubContext context, AuthenticationService authenticationService, AuthorizationService authorizationService, ILogger<GymsController> logger, FirebaseService firebaseService)
        {
            _gymsInfo = new GymsInfo(context, logger);
            _authenticationService = authenticationService;
            _logger = logger;
            _authorizationService = authorizationService;
            _firebaseService = firebaseService;
        }

        /// <summary>
        /// Displays the gym details based on the provided gym ID.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        // GET: Gyms?gymName=GymName
        public async Task<IActionResult> Index(int gymId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);
            _logger.LogInformation($"\n\n\n\n AQUI: {result.Gym.Images.Count}\n\n\n\n");
            if (result.IsAuthorizedToEdit)
            {
                ViewData["accountType"] = result.Account!.AccountType;
                return View("Edit", result.Gym);
            }

            if (result.IsAuthorizedToRead) ViewData["isMember"] = true;


            return View(result.Gym);
        }

        /// <summary>
        /// Displays the employees of the gym based on the provided gym ID.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> Employees(int gymId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.IsAuthorizedToEdit)
                return View("EmployeesEdit", result.Gym);

            if (result.IsAuthorizedToRead)
                return View(result.Gym);



            return RedirectToAction("Index", new { gymId = gymId });
        }// <summary>
        /// Displays the clients of the gym based on the provided gym ID.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> Clients(int gymId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.IsAuthorizedToEdit)
                return View("ClientsEdit", result.Gym);

            if (result.IsAuthorizedToRead)
                return View(result.Gym);



            return RedirectToAction("Index", new { gymId = gymId });
        }
        /// <summary>
        /// Displays the requests of the gym based on the provided gym ID.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> Requests(int gymId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.IsAuthorizedToEdit)
                return View("RequestsEdit", result.Gym);

            if (result.IsAuthorizedToRead)
                return View(result.Gym);


            return RedirectToAction("NotAuthorized");
        }

        /// <summary>
        /// Redirects to the Relationships action of a specific employee.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <param name="gymEmployeeId">The ID of the gym employee.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        [HttpPost]
        public IActionResult RelationshipsGymEmployee(int gymId, int? gymEmployeeId)
        {
            return RedirectToAction("Relationships", new { gymId = gymId, gymEmployeeId = gymEmployeeId });
        }
        /// <summary>
        /// Displays the relationships between gym employees and clients based on the provided gym ID and employee ID.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <param name="gymEmployeeId">The ID of the gym employee.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> Relationships(int gymId, int? gymEmployeeId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.Gym == null) return View("NotAuthorized");

            IEnumerable<GymClient>? clients = null;
            int? employAccountId = null;
            if (gymEmployeeId != null)
            {
                var employee = await _gymsInfo.GetGymEmployee((int)gymEmployeeId);
                clients = employee.GymClients.Select(rel => rel.GymClient);
                employAccountId = employee.Client.UserId;
            }


            if (result.IsAuthorizedToEdit)
            {
                ViewData["EmployeeClients"] = clients;
                ViewData["EmployeeAccountId"] = employAccountId;
                return View("RelationshipsEdit", result.Gym);
            }

            if (result.IsAuthorizedToRead)
            {
                ViewData["EmployeeClients"] = clients;
                ViewData["EmployeeAccountId"] = employAccountId;
                return View(result.Gym);
            }



            return View("NotAuthorized");
        }


        /// <summary>
        /// Displays the gym edit page based on the provided gym ID.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> EditGym(int gymId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.IsAuthorizedToEdit)
                return View(result.Gym);

            return View("NotAuthorized");
        }

        /// <summary>
        /// Handles the gym edit post request.
        /// </summary>
        /// <param name="newGym">The updated gym information.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(Gym? newGym)
        {
            if (newGym == null) return View("NotAuthorized");

            var result = await _authorizationService.isAuthorized(newGym.Id, HttpContext.Session);


            if (!result.IsAuthorizedToEdit)
                return View("NotAuthorized");

            await _gymsInfo.UpdateGym(newGym);

            return RedirectToAction("Index", new { gymId = newGym.Id });

        }


        /// <summary>
        /// Enlists a gym for the logged-in user.
        /// </summary>
        /// <param name="gymId">The ID of the gym to enlist.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> EnlistGym(int gymId)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.Gym == null || result.Account == null || result.Account.AccountType != AccountType.USER)
                return RedirectToAction("NotAuthorized");


            var client = await _gymsInfo.GetClient((User)result.Account);
            if (client == null) return RedirectToAction("NotAuthorized");

            await _gymsInfo.AddRequest(result.Gym, client);

            return RedirectToAction("Index", new { gymId = gymId });
        }
        /// <summary>
        /// Confirms a request for membership to the gym.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <param name="accountId">The ID of the account requesting membership.</param>
        /// <param name="role">The role of the account in the gym.</param>
        /// <returns>Returns the appropriate view based on authorization status.</returns>
        public async Task<IActionResult> ConfirmRequest(int gymId, int accountId, Role role)
        {
            var result = await _authorizationService.isAuthorized(gymId, HttpContext.Session);

            if (result.Gym == null || result.Account == null || !result.IsAuthorizedToEdit)
                return RedirectToAction("NotAuthorized");

            var accountToConfirm = await _authenticationService.GetAccount("id", accountId.ToString());
            if (accountToConfirm == null)
            {
                TempData["ResultMessage"] = "Account was not Confirmed! Something went Wrong!";
                return RedirectToAction("Requests", new { gymId = gymId });
            }


            var client = await _gymsInfo.GetClient((User)accountToConfirm);
            if (client == null)
            {
                TempData["ResultMessage"] = "Account was not Confirmed! Something went Wrong!";
                return RedirectToAction("Requests", new { gymId = gymId });
            }



            if (role == Role.CLIENT)
            {

Pv-Final/EasyFitHub/EasyFitHub/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyFitHub.Data;
using EasyFitHub.Models.Statistics;
using Microsoft.Extensions.Logging;

namespace EasyFitHub.Controllers
{
    /// <summary>
    /// AUTHOR: Francisco Silva
    /// Controller responsible for handling statistics-related actions in the application.
    /// </summary>
    public class StatisticsController : Controller
    {
        private readonly StatisticsInfo _statisticsInfo;
        private readonly ILogger<StatisticsController> _logger;


        public StatisticsController(EasyFitHubContext context, ILogger<StatisticsController> logger)
        {
            _logger = logger;
            _statisticsInfo = new StatisticsInfo(context, logger);
        }

        /// <summary>
        /// Retrieves platform-wide statistics.
        /// </summary>
        /// <returns>Returns a view displaying platform statistics.</returns>
        public async Task<IActionResult> PlatformStats()
        {
            var platformStats = await _statisticsInfo.GetPlatformStats();
            return View(platformStats);
        }

        /// <summary>
        /// Retrieves statistics for a specific gym.
        /// </summary>
        /// <param name="gymId">The ID of the gym.</param>
        /// <returns>Returns a view displaying statistics for the specified gym.</returns>
        public async Task<IActionResult> GymStats(int gymId)
        {
            var gymStats = await _statisticsInfo.GetGymStats(gymId);
            return View(gymStats);
        }

        /// <summary>
        /// Retrieves statistics for a specific employee.
        /// </summary>
        /// <param name="clientId">The ID of the employee.</param>
        /// <returns>Returns a view displaying statistics for the specified employee.</returns>
        public async Task<IActionResult> EmployeeStats(int clientId)
        {
            var employeeStats = await _statisticsInfo.GetEmployeeStats(clientId);
            return View(employeeStats);
        }

        /// <summary>
        /// Retrieves statistics for a specific client.
        /// </summary>
        /// <param name="clientId">The ID of the client.</param>
        /// <returns>Returns a view displaying statistics for the specified client.</returns>
        public async Task<IActionResult> ClientStats(int clientId)
        {
            var clientStats = await _statisticsInfo.GetClientStats(clientId);
            return View(clientStats);
        }

        /// <summary>
        /// Creates platform-wide statistics.
        /// </summary>
        /// <returns>Returns the elapsed time in milliseconds for creating the statistics.</returns>
        [HttpPost]
        public async Task<ActionResult<double>> CreatePlatformStats()
        {
            try
            {
                var stopwatch = new System.Diagnostics.Stopwatch();
                stopwatch.Start();

                await _statisticsInfo.CreateStats();

                stopwatch.Stop();
                double elapsedTime = stopwatch.Elapsed.TotalMilliseconds;

                _logger.LogInformation($"\n\n\n\nElapsed Time in Miliseconds: {elapsedTime}\n\n\n\n");

                return Ok(elapsedTime);
            }
            catch (Exception ex)
            {
                _logger.LogError($"An error occurred while creating platform statistics: {ex.Message}");
                return StatusCode(500, "An error occurred while creating platform statistics.");
            }
        }
    }
}

Pv-Final/EasyFitHub/EasyFitHub/Views/Home/GymList.cshtml
@using EasyFitHub.Models.Gym
@model List<Gym>
@*
    Author: Gonçalo V.
    View destinada à exploração de ginásios
*@
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/GymList.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fontsource-inter@4">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Istok+Web&display=swap">
</head>

@section Header {
    <div class="navbar2">
        <a href="@Url.Action("Index", "Authentication")"><img class="img2" src="/lib/imagens/Arrow.PNG" /></a>
        <p class="gymClients">GymList</p>
    </div>
}

<body>
    <br />
    <br />
    <div class="content">
        <div class="form-container">
            <form method="get" asp-action="GymList" asp-controller="Home">
                <label for="searchType">Search by:</label>
                <select class="dropdown-select" id="searchType" name="searchType">
                    <option value="name">Name</option>
                    <option value="location">Location</option>
                </select>
                <input type="text" id="searchInput" name="search" class="dropdown-select" />
                <label class="checkbox-container subscribed-label" id="subscribedLabel">
                    <input type="checkbox" id="favoriteCheckbox" name="subscribed">
                    <span class="checkmark"></span>
                    Subscribed
                </label>
                <button type="submit" class="button" id="searchButton">Search</button>
            </form>
            <form method="get" asp-action="GymList" asp-controller="Home">
                <button type="submit" class="button" name="searchType" value="clear">Clear</button>
            </form>
        </div>


        <br />
        <br />
        <br />
        <br />

        @foreach (var gym in Model)
        {
        
            <div class="gym-card">

                <a href=@Url.Action("Index", "Gyms", new { gymId = gym.Id})>
                @if (gym.Images != null && gym.Images.Any())
                {
                        <img src="@gym.Images.First().Path" style="width:450px;height:300px;" />
                }
                else
                {
                        <img class="image" src="/lib/imagens/GymDefault.jpg" style="width:450px;height:300px;" />
                }
                </a>
                <h3>@gym.Name</h3>
                <p>@gym.Description</p>
                <p>Location: @gym.Location</p>
                <p>Registration Date: @gym.RegisterDate.ToShortDateString()</p>

            </div>
        }
    </div>
</body>

@if (TempData["ResultMessage"] != null)
{
    <script>
        window.onload = function () {
            alert('@TempData["ResultMessage"]');
        };
    </script>
}

Pv-Final/EasyFitHub/EasyFitHub/Views/Home/Index.cshtml
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fontsource-inter@4">
    <link rel="stylesheet" href="~/css/MainPage.css" />
</head>
@*
    Author: Francisco Silva
    View que é a página principal do sistema
*@
@{
    ViewData["Title"] = "Home Page";
}

@section Header {
    <div class="navbar2">
        <a>
            <img class="img2" src="/lib/imagens/LogoPNG2.png" />
        </a>
        <ul class="navbar-items">
            <li class="nav-link active"><a href="@Url.Action("Index", "Home")" tabindex="4">Home</a></li>
            <li><a href="@Url.Action("PlatformStats", "Statistics")">Platform Statistics</a></li>
            @if (ViewData["AccountType"] != null && ViewData["AccountType"] as EasyFitHub.Models.Account.AccountType? == EasyFitHub.Models.Account.AccountType.MANAGER)
            {
                <li><a href=" @Url.Action("MyGym", "Home")" tabindex="4">My Gym</a></li>
            }
            else
            {
                <li><a href="@Url.Action("GymList", "Home")" tabindex="4">Gym Explorer</a></li>
            }
            @if (ViewData["AccountType"] != null && ViewData["AccountType"] as EasyFitHub.Models.Account.AccountType? == EasyFitHub.Models.Account.AccountType.USER)
            {
                <li><a href="@Url.Action("Index", "Plans", new { userId = ViewData["AccountId"] })" tabindex="4">Plans</a></li>
            }
            @if (ViewData["AccountType"] != null && ViewData["AccountType"] as EasyFitHub.Models.Account.AccountType? == EasyFitHub.Models.Account.AccountType.ADMIN)
            {
                <li><a href=" @Url.Action("ConfirmGyms", "Gyms")" tabindex="4">Admin Hub</a></li>
            }
            @if (ViewData["AccountId"] != null)
            {
                <li><a href=" @Url.Action("Logout", "Authentication")" tabindex="4">Sign Out</a></li>
            }
            else
            {
                <li><a href=" @Url.Action("Index", "Authentication")" tabindex="4">Sign In</a></li>
            }

        </ul>
    </div>
    <div class="navbar3">
        <a href="@{
            if(ViewData["AccountId"] != null)
            {
                        @Url.Action("Index", "Profile", new { userId = ViewData["AccountId"] })
;
            }
            else
            {
                        @Url.Action("Index", "Authentication")
;
            }
        }">
            <img class="img3" src="/lib/imagens/ProfileV2.PNG" />
        </a>
    </div>
}

<body>
    <div class="text-center">
        <h1 class="display-4">Welcome to</h1><br />
    </div>
    <div>
        <img class="img1" src="/lib/imagens/LogoPNG2.png" />
    </div>
    <div class="text-center2">
        <h4 class="display-5">YOU’RE THE ONLY ONE THAT CAN MAKE A</h4><br />
        <h4 class="display-6">CHANGE</h4><br />
    </div>
    <div class="form-button">
        @if (ViewData["AccountId"] == null)
        {
            <a href="@Url.Action("Registration", "Authentication", new { accountType = "user" })">
                <button type="submit" class="btn btn-primary">
                    Start Today
                </button>
            </a>
        }
    </div>
</body>

@if (TempData["ResultMessage"] != null)
{
    <script>
        window.onload = function () {
            alert('@TempData["ResultMessage"]');
        };
    </script>
}